# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, b'USER'), (2, b'ORGANISER')], default=1),
        ),
    ]
