# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0002_auto_20160109_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('eventPreferences', models.ManyToManyField(to='sundayfunday.Event')),
                ('userPreferences', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
