# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0003_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='eventPreferences',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='userPreferences',
        ),
        migrations.AddField(
            model_name='event',
            name='preferences',
            field=models.ManyToManyField(to='sundayfunday.Preferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(to='sundayfunday.Preferences'),
        ),
    ]
