# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0004_auto_20160109_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='name',
            new_name='title',
        ),
    ]
