# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0005_auto_20160109_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='title',
            new_name='name',
        ),
    ]
