# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0006_auto_20160109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='sundayfunday.Preferences'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='sundayfunday.Preferences'),
        ),
    ]
