# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0007_auto_20160109_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sundayfunday.Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, to='sundayfunday.Comments'),
        ),
    ]
