# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0008_auto_20160109_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='preferences',
            new_name='preference',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='preferences',
            new_name='preference',
        ),
    ]
