# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0012_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, b'POOR'), (2, b'FAIR'), (3, b'AVERAGE'), (4, b'GOOD'), (5, b'EXCELLENT')], default=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayfunday.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
