# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayfunday', '0014_auto_20160109_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='id',
        ),
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
